const universidadesConstant: any = {
    "universidades" : [
        { name: "Universidade de São Paulo", acronym: "USP" },
        { name: "Universidade Estadual de Campinas", acronym: "UNICAMP" },
        { name: "Universidade Federal do Rio de Janeiro", acronym: "UFRJ" },
        { name: "Universidade Estadual Paulista", acronym: "UNESP" },
        { name: "Universidade Federal de Minas Gerais", acronym: "UFMG" },
        { name: "Universidade Federal do Rio Grande do Sul", acronym: "UFRGS" },
        { name: "Universidade de Brasília", acronym: "UnB" },
        { name: "Universidade Federal de Santa Catarina", acronym: "UFSC" },
        { name: "Universidade Federal do Paraná", acronym: "UFPR" },
        { name: "Pontifícia Universidade Católica do Rio de Janeiro", acronym: "PUC-Rio" },
        { name: "Universidade Federal de Pernambuco", acronym: "UFPE" },
        { name: "Universidade Estadual de Londrina", acronym: "UEL" },
        { name: "Universidade Federal de Goiás", acronym: "UFG" },
        { name: "Universidade Federal do Ceará", acronym: "UFC" },
        { name: "Universidade Federal de São Carlos", acronym: "UFSCar" },
        { name: "Universidade Estadual do Ceará", acronym: "UECE" },
        { name: "Universidade Federal da Bahia", acronym: "UFBA" },
        { name: "Universidade Federal do Espírito Santo", acronym: "UFES" },
        { name: "Universidade Estadual de Maringá", acronym: "UEM" },
        { name: "Universidade Federal do Mato Grosso", acronym: "UFMT" },
        { name: "Universidade Federal de Alagoas", acronym: "UFAL" },
        { name: "Universidade Estadual do Norte do Paraná", acronym: "UENP" },
        { name: "Universidade Federal de Roraima", acronym: "UFRR" },
        { name: "Pontifícia Universidade Católica do Paraná", acronym: "PUC-PR" },
        { name: "Universidade do Estado do Rio de Janeiro", acronym: "UERJ" },
        { name: "Universidade Federal da Paraíba", acronym: "UFPB" },
        { name: "Universidade Federal do Amazonas", acronym: "UFAM" },
        { name: "Universidade Federal de Mato Grosso do Sul", acronym: "UFMS" },
        { name: "Universidade Federal do Acre", acronym: "UFAC" },
        { name: "Universidade Federal de Lavras", acronym: "UFLA" },
        { name: "Universidade Federal Fluminense", acronym: "UFF"},
        { name: "Harvard University", acronym: "HU" },
        { name: "Massachusetts Institute of Technology", acronym: "MIT" },
        { name: "Stanford University", acronym: "SU" },
        { name: "University of Cambridge", acronym: "UC" },
        { name: "University of Oxford", acronym: "UO" },
        { name: "California Institute of Technology", acronym: "Caltech" },
        { name: "Princeton University", acronym: "PU" },
        { name: "Yale University", acronym: "YU" },
        { name: "University of Chicago", acronym: "UChicago" },
        { name: "Imperial College London", acronym: "ICL" },
        { name: "Columbia University", acronym: "CU" },
        { name: "University of Toronto", acronym: "UofT" },
        { name: "ETH Zurich", acronym: "ETH" },
        { name: "University of California, Berkeley", acronym: "UCB" },
        { name: "University of Melbourne", acronym: "UMelb" },
        { name: "University of Tokyo", acronym: "UTokyo" },
        { name: "Peking University", acronym: "PKU" },
        { name: "National University of Singapore", acronym: "NUS" },
        { name: "University of Hong Kong", acronym: "HKU" },
        { name: "Australian National University", acronym: "ANU" },
        { name: "University of Edinburgh", acronym: "UoE" },
        { name: "London School of Economics", acronym: "LSE" },
        { name: "Tsinghua University", acronym: "Tsinghua" },
        { name: "University of California, Los Angeles", acronym: "UCLA" },
        { name: "University of Copenhagen", acronym: "UCPH" },
        { name: "University of Munich", acronym: "LMU" },
        { name: "University of Sydney", acronym: "USyd" },
        { name: "King's College London", acronym: "KCL" },
        { name: "University of Pennsylvania", acronym: "UPenn" },
        { name: "Johns Hopkins University", acronym: "JHU" }
    ]
  }


export default universidadesConstant;